LD_FILE = boards/samd21x18-bootloader-external-flash-crystalless.ld
USB_VID = 0x1208
USB_PID = 0x1974
USB_PRODUCT = "Music Thing M0 Plus"
USB_MANUFACTURER = "Music Thing"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICE_COUNT = 1
EXTERNAL_FLASH_DEVICES = "W25Q64JV_IQ"
LONGINT_IMPL = MPZ

CIRCUITPY_BITBANG_APA102 = 1

CIRCUITPY_BITBANGIO = 0
CIRCUITPY_GAMEPAD = 0
CIRCUITPY_I2CSLAVE = 0
CIRCUITPY_RTC = 0

CFLAGS_INLINE_LIMIT = 60
SUPEROPT_GC = 0

