LD_FILE = boards/samd21x18-bootloader.ld
USB_VID = 0x1208
USB_PID = 0x1973
USB_PRODUCT = "Music Thing M0"
USB_MANUFACTURER = "Music Thing"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_SMALL_BUILD = 1

SUPEROPT_GC = 0